# TestProject - テトリスゲーム開発設定

# プロジェクト基本情報
project:
  name: "TestProject - Tetris Game"
  description: "AIエージェントを活用したブラウザテトリスゲーム開発"
  version: "1.0.0"
  start_date: "2024-01-15"
  technology_stack:
    - "HTML5"
    - "CSS3"
    - "JavaScript (ES6+)"
    - "Canvas API"

# スプリント設定
sprint:
  length: 14  # 日数
  working_days: 10  # 営業日
  start_time: "09:00"
  end_time: "18:00"
  timezone: "Asia/Tokyo"
  current_sprint: 1

# チーム設定
team:
  size: 5
  roles:
    - "Product Owner"
    - "Scrum Master"
    - "Frontend Developer"
    - "Game Developer"
    - "QA Tester"

# ベロシティ・品質目標
targets:
  velocity: 15  # ストーリーポイント/スプリント（初回想定）
  quality_threshold: 0.8
  test_coverage_threshold: 0.8
  code_review_threshold: 1  # 最低レビュー人数
  bug_density_threshold: 0.1  # bugs/KLOC
  performance_target: 60  # FPS

# AIエージェント設定
ai_agents:
  automation_level: "high"  # low/medium/high
  
  development_agent:
    enabled: true
    schedule: "continuous"
    quality_threshold: 0.8
    auto_commit: false
    auto_test: true
    specialization:
      - "JavaScript game development"
      - "Canvas API"
      - "Game loop optimization"
  
  testing_agent:
    enabled: true
    schedule: "on_commit"
    test_types:
      - "unit"
      - "integration"
      - "e2e"
      - "performance"
    coverage_threshold: 0.8
    game_specific_tests:
      - "tetromino_logic"
      - "collision_detection"
      - "line_clearing"
  
  documentation_agent:
    enabled: true
    schedule: "daily"
    auto_update: true
    formats:
      - "markdown"
      - "html"
    focus_areas:
      - "game_mechanics"
      - "api_documentation"
      - "user_guide"
  
  progress_tracking_agent:
    enabled: true
    schedule: "daily"
    update_time: "18:00"
    alert_threshold: 0.2  # 20%の乖離でアラート

# 通知・アラート設定
notifications:
  slack:
    enabled: false
    webhook_url: ""
    channels:
      - "#tetris-development"
      - "#scrum-updates"
  
  email:
    enabled: false
    smtp_server: ""
    recipients:
      - "team@example.com"
  
  alerts:
    burndown_deviation: 0.2  # 20%
    test_coverage_drop: 0.1  # 10%
    build_failure_count: 3
    overdue_pbi: true
    performance_degradation: true  # FPS低下

# 品質ゲート設定
quality_gates:
  code_quality:
    eslint:
      enabled: true
      config: ".eslintrc.js"
      rules:
        - "no-unused-vars"
        - "no-console"
        - "prefer-const"
    
    prettier:
      enabled: true
      config: ".prettierrc"
  
  security:
    dependency_check: true
    vulnerability_scan: false  # フロントエンドのみのため
    secret_detection: false
  
  performance:
    fps_threshold: 60
    memory_leak_detection: true
    load_time_threshold: 2000  # ms
    lighthouse_score: 90

# ゲーム固有設定
game_settings:
  tetris:
    grid_size:
      width: 10
      height: 20
    tetrominos:
      - "I"
      - "O" 
      - "T"
      - "S"
      - "Z"
      - "J"
      - "L"
    scoring:
      single_line: 100
      double_line: 300
      triple_line: 500
      tetris: 800
    controls:
      move_left: "ArrowLeft"
      move_right: "ArrowRight"
      rotate: "ArrowUp"
      soft_drop: "ArrowDown"
      hard_drop: "Space"

# レポート設定
reports:
  daily_standup:
    enabled: true
    time: "09:00"
    template: "docs/templates/daily-standup-template.md"
  
  progress_dashboard:
    enabled: true
    update_frequency: "daily"
    template: "docs/templates/progress-dashboard-template.md"
    game_metrics:
      - "fps_performance"
      - "memory_usage"
      - "feature_completion"
  
  sprint_review:
    enabled: true
    auto_generate: true
    include_metrics: true
    demo_preparation: true
  
  burndown_chart:
    enabled: true
    update_frequency: "daily"
    format: ["png", "svg"]

# ファイルパス設定
paths:
  docs_root: "docs/"
  templates: "docs/templates/"
  product_backlog: "docs/product-backlog/"
  sprints: "docs/sprints/"
  burndown_charts: "docs/burndown-charts/"
  velocity_tracking: "docs/velocity-tracking/"
  metrics: "docs/metrics/"
  ai_agents: "docs/ai-agents/"
  automation: "docs/automation/"
  game_source: "src/"
  game_assets: "assets/"
  tests: "tests/"

# 統合設定
integrations:
  github:
    enabled: false
    repository: ""
    branch_protection: true
    auto_deploy_pages: true  # GitHub Pagesでのデモ公開
  
  browser_testing:
    enabled: true
    browsers:
      - "Chrome"
      - "Firefox" 
      - "Safari"
      - "Edge"
    mobile_testing: true

# 環境設定
environments:
  development:
    auto_deploy: true
    test_coverage_required: 0.7
    debug_mode: true
    fps_monitoring: true
  
  staging:
    auto_deploy: false
    test_coverage_required: 0.8
    performance_test: true
    cross_browser_test: true
  
  production:
    auto_deploy: false
    test_coverage_required: 0.9
    performance_test: true
    minification: true
    compression: true

---
# 設定ファイル更新履歴
# 2024-01-15: テトリスゲーム開発用に初期設定作成
# 2024-01-15: ゲーム固有設定、パフォーマンス監視設定追加 